# Generated by Django 2.0.2 on 2019-01-19 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nom carte', max_length=200)),
                ('cost', models.IntegerField(default=0)),
                ('health', models.IntegerField(default=0)),
                ('attack', models.IntegerField(default=0)),
                ('text', models.TextField(default='Texte carte')),
                ('img', models.CharField(default='Image carte', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nom deck', max_length=200)),
                ('cost', models.IntegerField(default=0)),
                ('official', models.BooleanField(default=False)),
                ('img', models.CharField(default='Image carte', max_length=255)),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deck_Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcore.Card')),
                ('deck_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcore.Deck')),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange_Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_assignee', models.IntegerField(default=0)),
                ('card_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcore.Card')),
                ('exchange_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_card', to='appcore.Exchange')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Titre post', max_length=200)),
                ('date', models.DateField(null=True)),
                ('content', models.TextField(default='Contenu post')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treasure', models.IntegerField(default=400)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nom room', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User_Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcore.Card')),
                ('user_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='room',
            field=models.ManyToManyField(blank=True, to='appcore.Room'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ManyToManyField(blank=True, through='appcore.Deck_Card', to='appcore.Deck'),
        ),
        migrations.AddField(
            model_name='card',
            name='exchange',
            field=models.ManyToManyField(blank=True, through='appcore.Exchange_Card', to='appcore.Exchange'),
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ManyToManyField(blank=True, through='appcore.User_Card', to=settings.AUTH_USER_MODEL),
        ),
    ]
