# Generated by Django 2.0.2 on 2018-11-17 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nom carte', max_length=200)),
                ('cost', models.IntegerField(default=0)),
                ('health', models.IntegerField(default=0)),
                ('attack', models.IntegerField(default=0)),
                ('text', models.TextField(default='Texte carte')),
                ('img', models.CharField(default='Image carte', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nom deck', max_length=200)),
                ('cost', models.IntegerField(default=0)),
                ('official', models.BooleanField(default=False)),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deck_Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcore.Card')),
                ('deck_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcore.Deck')),
            ],
        ),
        migrations.CreateModel(
            name='User_Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcore.Card')),
                ('user_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ManyToManyField(blank=True, through='appcore.Deck_Card', to='appcore.Deck'),
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ManyToManyField(blank=True, through='appcore.User_Card', to=settings.AUTH_USER_MODEL),
        ),
    ]
