# Generated by Django 2.0.2 on 2018-11-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='img',
            field=models.CharField(default='Image carte', max_length=255),
        ),
    ]
