# Generated by Django 2.0.2 on 2018-09-30 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0002_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
