# Generated by Django 2.0.2 on 2018-09-30 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
