# Generated by Django 2.0.2 on 2018-11-25 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0005_exchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange_Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_assignee', models.BooleanField(default=False)),
                ('card_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcore.Card')),
            ],
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='cards_assignee',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='cards_creator',
        ),
        migrations.AddField(
            model_name='exchange_card',
            name='exchange_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcore.Exchange'),
        ),
        migrations.AddField(
            model_name='card',
            name='exchange',
            field=models.ManyToManyField(blank=True, through='appcore.Exchange_Card', to='appcore.Exchange'),
        ),
    ]
