# Generated by Django 2.0.2 on 2018-11-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0006_auto_20181125_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange_card',
            name='creator_assignee',
            field=models.IntegerField(default=0),
        ),
    ]
