# Generated by Django 2.0.2 on 2018-11-25 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0007_auto_20181125_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange_card',
            name='exchange_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_card', to='appcore.Exchange'),
        ),
    ]
