# Generated by Django 2.0.2 on 2018-10-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0007_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='treasure',
            field=models.IntegerField(default=400),
        ),
    ]
