# Generated by Django 2.0.2 on 2018-11-26 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0008_auto_20181125_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck_card',
            name='card_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcore.Card'),
        ),
        migrations.AlterField(
            model_name='deck_card',
            name='deck_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcore.Deck'),
        ),
        migrations.AlterField(
            model_name='exchange_card',
            name='card_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcore.Card'),
        ),
        migrations.AlterField(
            model_name='exchange_card',
            name='exchange_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_card', to='appcore.Exchange'),
        ),
        migrations.AlterField(
            model_name='user_card',
            name='card_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcore.Card'),
        ),
        migrations.AlterField(
            model_name='user_card',
            name='user_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
