# Generated by Django 2.0.2 on 2018-12-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0009_auto_20181126_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nom room', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='room',
            field=models.ManyToManyField(blank=True, to='appcore.Room'),
        ),
    ]
