# Generated by Django 2.0.2 on 2018-10-02 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0009_auto_20181002_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
