# Generated by Django 2.0.2 on 2018-10-02 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0012_auto_20181002_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='user',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
