# Generated by Django 2.0.2 on 2018-10-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0014_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='attack',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='health',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
