# Generated by Django 2.0.2 on 2018-10-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0017_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='cost',
            field=models.IntegerField(null=True),
        ),
    ]
