# Generated by Django 2.0.2 on 2018-10-25 18:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0021_auto_20181025_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='cardsAssignee',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='cardsCreator',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None), size=None),
        ),
    ]
