# Generated by Django 2.0.2 on 2018-10-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0022_auto_20181025_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
