# Generated by Django 2.0.2 on 2018-10-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0023_deck_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='defaultDeck',
            field=models.BooleanField(default=False),
        ),
    ]
