# Generated by Django 2.0.2 on 2018-10-28 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0027_defaultcard_defaultdeck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultdeck',
            name='user',
        ),
    ]
