# Generated by Django 2.0.2 on 2018-10-28 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0028_remove_defaultdeck_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultCard',
        ),
        migrations.DeleteModel(
            name='DefaultDeck',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='defaultDeck',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='name',
        ),
    ]
