# Generated by Django 2.0.2 on 2018-10-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0030_cardorigins_deckorigins'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardOrigins',
            new_name='CardOrigin',
        ),
        migrations.RenameModel(
            old_name='DeckOrigins',
            new_name='DeckOrigin',
        ),
    ]
