# Generated by Django 2.0.2 on 2018-10-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0031_auto_20181028_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckorigin',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
