# Generated by Django 2.0.2 on 2018-10-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0032_deckorigin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
