# Generated by Django 2.0.2 on 2018-11-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0036_fight'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='health_opponent',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fight',
            name='health_user',
            field=models.IntegerField(null=True),
        ),
    ]
