# Generated by Django 2.0.2 on 2018-11-16 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appcore', '0037_auto_20181111_1347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardOrigin',
        ),
        migrations.DeleteModel(
            name='DeckOrigin',
        ),
        migrations.RemoveField(
            model_name='card',
            name='user',
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
