# Generated by Django 2.0.2 on 2018-11-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0038_auto_20181116_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='img',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
