# Generated by Django 2.0.2 on 2018-11-16 22:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appcore', '0039_card_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='cards',
        ),
        migrations.AddField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(default=None, to='appcore.Card'),
        ),
        migrations.RemoveField(
            model_name='deck',
            name='user',
        ),
        migrations.AddField(
            model_name='deck',
            name='user',
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
