# Generated by Django 2.0.2 on 2018-11-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0040_auto_20181116_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='official',
            field=models.BooleanField(default=False),
        ),
    ]
