# Generated by Django 2.0.2 on 2018-11-17 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0043_auto_20181117_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='deck',
            field=models.ManyToManyField(blank=True, to='appcore.Deck'),
        ),
        migrations.AlterField(
            model_name='card',
            name='health',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='img',
            field=models.CharField(default='Image carte', max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(default='Nom carte', max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='text',
            field=models.TextField(default='Texte carte'),
        ),
        migrations.AlterField(
            model_name='card',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deck',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deck',
            name='name',
            field=models.CharField(default='Nom deck', max_length=200),
        ),
        migrations.AlterField(
            model_name='deck',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
